### ISSUE TITLE
None value in train test output

### ISSUE THREAD

**Issue by snoberger** [cs540-testers/hw4-tester#5]
I am currently failing the test ```def test_train(self):``` due to the output

Traceback (most recent call last):
  File "test.py", line 176, in test_train
    self.compare_dicts(model, expected_model)
  File "test.py", line 34, in compare_dicts
    self.assertEqual(a[k], b[k])
AssertionError: Lists differ: ['.', 'a', None] != ['.', 'a']

First list contains 1 additional elements.
First extra element 2:
None

- ['.', 'a', None]
?          ------

+ ['.', 'a']

----------------------------------------------------------------------
Ran 9 tests in 22.451s

However when I run my code like it is in the test this is not the same output

model = train('./EasyFiles/', 2)
print(model)

has output
{'vocabulary': ['.', 'a'], 'log prior': {'2020': -0.916290731874155, '2016': -0.5108256237659905}, 'log p(w|y=2016)': {'.': -1.7047480922384253, 'a': -1.2992829841302609, None: -0.6061358035703157}, 'log p(w|y=2020)': {'.': -1.6094379124341005, 'a': -2.302585092994046, None: -0.35667494393873267}}

which is what the output should be.

**Comment by StephenJasina** [comment]
Verified that calling `train('./EasyFiles/', 2)` in different contexts yields different return values, so this is not an issue with the tester.
